import Footer from "../Components/UserShared/Footer/Footer";
import Navbar from "../Components/UserShared/Navbar/Navbar";
import "../globals.css";


export const metadata = {
  title: "NextLaw",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
